[package]
name = "block_index"
version = "0.1.0"
edition = "2021"
rust-version = "1.71.0"

[dependencies]
bitcoin = "0.32.5"
bdk_chain = { version = "0.21.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
